Updates for 2023 (#3)

diff --git a/scripts/lint-go b/scripts/lint-go
--- a/scripts/lint-go
+++ b/scripts/lint-go
@@ -1,4 +1,4 @@
-#!/bin/bash
+#! /usr/bin/env bash
 
 # =================================================================
 #
@@ -11,9 +11,24 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 set -eu
 
 # move up a directory
-cd $DIR/..
+cd "${DIR}"/..
 
 pkgs=$(go list ./... | grep -v /vendor/ | tr "\n" " ")
+
+check_command () {
+  cmd=$1
+
+  if ! command -v "bin/${cmd}" > /dev/null; then
+    echo "Missing ${cmd}, please install into bin/ directory with 'make bin/${cmd}'"
+    exit 1
+  fi
+}
+
+# Validate that the commands exist
+check_command errcheck
+check_command misspell
+check_command shadow
+check_command staticcheck
 
 echo "******************"
 echo "Running go vet"
@@ -25,8 +40,8 @@ echo "******************"
 echo "Running errcheck"
 bin/errcheck ${pkgs}
 echo "******************"
-echo "Running ineffassign"
-bin/ineffassign ./test
-echo "******************"
 echo "Running staticcheck"
 bin/staticcheck -checks all ${pkgs}
+echo "******************"
+echo "Running misspell"
+bin/misspell -locale US -error *.md *.go
